export default {
  math: {
    AG: 'Algebraic Geometry',
    AT: 'Algebraic Topology',
    AP: 'Analysis of PDEs',
    CT: 'Category Theory',
    CA: 'Classical Analysis and ODEs',
    CO: 'Combinatorics',
    AC: 'Communicative Algebra',
    CV: 'Complex Variables',
    DF: 'Differentil Geometry',
    DS: 'Dynamical Systems',
    FA: 'Functional Analysis',
    GM: 'General Math',
    GN: 'General Topology',
    GT: 'Geometric Topology',
    GR: 'Group Theory',
    HO: 'History and Overview',
    IT: 'Information Theory',
    KT: 'K-Theory and Homology',
    LO: 'Logic',
    MP: 'Mathematical Physics',
    MG: 'Metric Geometry',
    NT: 'Number Theory',
    NA: 'Numerical  Analysis',
    OA: 'Operator Algebras',
    OC: 'Optimization and Control',
    PR: 'Probability',
    QA: 'Quantum Algebra',
    RT: 'Representation Theory',
    RA: 'Rings and Algebra',
    SP: 'Spectral Theory',
    ST: 'Statistics Theory',
    SG: 'Symplectic Geometry'
  },
  physics: {
    'acc-ph': 'Accelerator Physics',
    'ao-ph': 'Atmospheric and Oceanic Physics',
    'atom-ph': 'Atomic Physics',
    'atm-clus': 'Atomic and Molecular Clusters',
    'bio-ph': 'Biological Physics',
    'chem-ph': 'Chemical Physics',
    'class-ph': 'Classical Physics',
    'comp-ph': 'Computational Physics',
    'data-an': 'Data Analysis, Statistics and Probability',
    'flu-dyn': 'Fluid Dynamics',
    'gen-ph': 'General Physics',
    'geo-ph': 'Geophysics',
    'hist-ph': 'History and Philosophy of Physics',
    'ins-det': 'Instrumentation and Detectors',
    'med-ph': 'Medical Physics',
    optics: 'Optics',
    'ed-ph': 'Physics Education',
    'soc-ph': 'Physics and Society',
    'plasm-ph': 'Plasma Physics',
    'pop-ph': 'Popular Physics',
    'space-ph': 'Space Physics'
  },
  stat: {
    AP: 'Applications',
    CO: 'Computation',
    ML: 'Machine Learning',
    ME: 'Methodology',
    OT: 'Other Statistics',
    TH: 'Statistics Theory'
  }
};



